# Introduction to Numpy 

## Intro


In [1]:
import numpy as np

def getDir(module):
    print(", ".join(dir(module)))

In [2]:
getDir(np)

ALLOW_THREADS, AxisError, BUFSIZE, CLIP, ComplexWarning, DataSource, ERR_CALL, ERR_DEFAULT, ERR_IGNORE, ERR_LOG, ERR_PRINT, ERR_RAISE, ERR_WARN, FLOATING_POINT_SUPPORT, FPE_DIVIDEBYZERO, FPE_INVALID, FPE_OVERFLOW, FPE_UNDERFLOW, False_, Inf, Infinity, MAXDIMS, MAY_SHARE_BOUNDS, MAY_SHARE_EXACT, MachAr, ModuleDeprecationWarning, NAN, NINF, NZERO, NaN, PINF, PZERO, PackageLoader, RAISE, RankWarning, SHIFT_DIVIDEBYZERO, SHIFT_INVALID, SHIFT_OVERFLOW, SHIFT_UNDERFLOW, ScalarType, Tester, TooHardError, True_, UFUNC_BUFSIZE_DEFAULT, UFUNC_PYVALS_NAME, VisibleDeprecationWarning, WRAP, _NoValue, __NUMPY_SETUP__, __all__, __builtins__, __cached__, __config__, __doc__, __file__, __git_revision__, __loader__, __mkl_version__, __name__, __package__, __path__, __spec__, __version__, _distributor_init, _globals, _import_tools, _mat, _mklinit, _numpy_tester, abs, absolute, absolute_import, add, add_docstring, add_newdoc, add_newdoc_ufunc, add_newdocs, alen, all, allclose, alltrue, amax, amin, angle, 

## Initialization


In [3]:
# from an array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
np.zeros(20).reshape(4,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones(20).reshape(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
np.random.randn(20).reshape(4,5)

array([[-1.2202318 , -2.02110008,  1.91861547, -2.06401664, -0.12908384],
       [-0.46812502,  0.7700364 , -0.24518601, -0.90728285,  0.12127973],
       [ 0.22632743, -0.25379683,  0.11779245,  0.47986639, -0.86141155],
       [ 0.22830722, -0.40919636, -0.21415245, -0.1738128 , -1.496992  ]])

## Dimensions


In [8]:
arr = np.random.randn(100).reshape(2,10,5)
arr

array([[[-0.73517662,  0.76746321,  0.56945603, -0.97179283,
         -0.20789741],
        [ 0.09780711,  0.61033636, -1.64822527, -1.41929007,
          0.2659226 ],
        [-1.44234747, -0.61327993, -1.30996604,  0.45169889,
         -0.40499353],
        [ 0.75220265, -1.9710048 , -0.22395933, -0.94216945,
         -0.43806704],
        [ 0.89328412,  1.85595809, -1.01262965,  0.17255281,
         -0.0861993 ],
        [ 2.92281179, -1.16172829,  0.01917341, -0.8776952 ,
          0.74112912],
        [-0.0575754 , -0.64680914,  0.09174234,  1.41321019,
         -0.49819393],
        [-0.00830231, -1.02048376, -0.14047228,  0.6827966 ,
         -1.13218768],
        [-0.56905938, -0.91109151,  0.3240663 ,  1.58145601,
         -0.0648197 ],
        [ 1.27897383, -0.55957065, -0.81395518,  1.73873724,
         -0.82470823]],

       [[-0.98655053, -0.9813287 ,  0.61893184,  0.16067876,
          1.04867792],
        [ 2.17567522, -0.75154638,  1.24102932,  1.17699733,
         -0.9

In [9]:
arr.shape

(2, 10, 5)

## Indexing


### [dimension 1 specifications,dimension 2 specifications.......] 

In [10]:
# fills all with 4's
arr[:,:,:] = 4
arr

array([[[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]]])

In [11]:
# Fills the first collection of matrices with -1's
arr[0,:,:] = -1
arr

array([[[-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.]],

       [[ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.]]])

In [12]:
# Fills the second row of first big matrix with 50's
arr[0,1,:] = 50
arr

array([[[-1., -1., -1., -1., -1.],
        [50., 50., 50., 50., 50.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.]],

       [[ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.,  4.]]])

In [13]:
# Fills the 2nd 2-d matrix's section of 8th to last index(row-wise) and 3rd to last index(column-wise)
arr[1,7:,2:] = 1000
arr

array([[[  -1.,   -1.,   -1.,   -1.,   -1.],
        [  50.,   50.,   50.,   50.,   50.],
        [  -1.,   -1.,   -1.,   -1.,   -1.],
        [  -1.,   -1.,   -1.,   -1.,   -1.],
        [  -1.,   -1.,   -1.,   -1.,   -1.],
        [  -1.,   -1.,   -1.,   -1.,   -1.],
        [  -1.,   -1.,   -1.,   -1.,   -1.],
        [  -1.,   -1.,   -1.,   -1.,   -1.],
        [  -1.,   -1.,   -1.,   -1.,   -1.],
        [  -1.,   -1.,   -1.,   -1.,   -1.]],

       [[   4.,    4.,    4.,    4.,    4.],
        [   4.,    4.,    4.,    4.,    4.],
        [   4.,    4.,    4.,    4.,    4.],
        [   4.,    4.,    4.,    4.,    4.],
        [   4.,    4.,    4.,    4.,    4.],
        [   4.,    4.,    4.,    4.,    4.],
        [   4.,    4.,    4.,    4.,    4.],
        [   4.,    4., 1000., 1000., 1000.],
        [   4.,    4., 1000., 1000., 1000.],
        [   4.,    4., 1000., 1000., 1000.]]])

In [14]:
arr[1,3,2] = 60
arr

array([[[  -1.,   -1.,   -1.,   -1.,   -1.],
        [  50.,   50.,   50.,   50.,   50.],
        [  -1.,   -1.,   -1.,   -1.,   -1.],
        [  -1.,   -1.,   -1.,   -1.,   -1.],
        [  -1.,   -1.,   -1.,   -1.,   -1.],
        [  -1.,   -1.,   -1.,   -1.,   -1.],
        [  -1.,   -1.,   -1.,   -1.,   -1.],
        [  -1.,   -1.,   -1.,   -1.,   -1.],
        [  -1.,   -1.,   -1.,   -1.,   -1.],
        [  -1.,   -1.,   -1.,   -1.,   -1.]],

       [[   4.,    4.,    4.,    4.,    4.],
        [   4.,    4.,    4.,    4.,    4.],
        [   4.,    4.,    4.,    4.,    4.],
        [   4.,    4.,   60.,    4.,    4.],
        [   4.,    4.,    4.,    4.,    4.],
        [   4.,    4.,    4.,    4.,    4.],
        [   4.,    4.,    4.,    4.,    4.],
        [   4.,    4., 1000., 1000., 1000.],
        [   4.,    4., 1000., 1000., 1000.],
        [   4.,    4., 1000., 1000., 1000.]]])

In [14]:
# 2d matrix
arr2 = np.arange(50).reshape(5,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [15]:
arr2.shape

(5, 10)

In [16]:
# taking sum along rows: there will be a sum value for each column so 10 values
# think of it as squeezing the dataframe along the first dimension, only the second dimension now remains
arr2.sum(axis = 0)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [17]:
# taking sum along columns: there will be a value of sum for each row
# similarly, you can think of this as squeezing along the second dimension, only the first dimension remains
print("your array:",arr2.sum(axis = 1))
print("shape of your array:",arr2.sum(axis = 1).shape)

your array: [ 45 145 245 345 445]
shape of your array: (5,)


In [18]:
# instead of sum, you can also calculate mean along an axis
arr2.mean(axis = 0)

array([20., 21., 22., 23., 24., 25., 26., 27., 28., 29.])

In [19]:
# standard deviation
arr2.std()

14.430869689661812

# nan values

In [21]:
# nan stands for not a number.. in numpy operations alone you won't come along this term all that much
# In numpy nan is:
np.nan

nan

In [22]:
# To check whether if a value is null or not
val = np.nan
np.isnan(val)

True

## Matrix operations


In [23]:
# dimensions 2 X 5
m1 = np.array([[1,2,3,4,5],[5,4,3,2,1]])

# dimensions 2 X 2
m2 = np.array([[2,3],[-3,-2]])

In [24]:
m2.dot(m1)

array([[ 17,  16,  15,  14,  13],
       [-13, -14, -15, -16, -17]])

In [25]:
m3 = [[2,2],[-2,-2]]

m4 = m3 * m2
m4

array([[4, 6],
       [6, 4]])

In [26]:
# scalar addition - value being added gets added to every term
m4 + 1

array([[5, 7],
       [7, 5]])

In [27]:
# scalar multiplication and division can also be done
m4 * 2

array([[ 8, 12],
       [12,  8]])

## broadcasting
### You can add a 2-D matrix to a row vector (1-D matrix). But for that, the number of columns should be same as size of the row vector

In [28]:
# size of row vector is 4
arr1 = np.array([1,2,3,4])

# Number of columns is 4: same as the size of row vector
arr2 = np.arange(20).reshape(5,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
# Broadcasting: for each row, element wise addition happens
arr1 + arr2

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13, 15, 17, 19],
       [17, 19, 21, 23]])