In [1]:
# open cv example to convert an image to grayscale
import numpy as np
import cv2

In [3]:
import os
# load image
img = cv2.imread(os.path.join(os.getcwd(),'demo images','butterfly.jpeg'))

In [4]:
# let's study the image first
print(type(img))
print(img.shape)

<class 'numpy.ndarray'>
(177, 284, 3)


In [5]:
# img is a numpy array
img

array([[[ 20, 153, 120],
        [ 18, 151, 118],
        [ 14, 148, 112],
        ...,
        [  8, 108,  80],
        [  6, 108,  80],
        [  6, 109,  81]],

       [[ 20, 153, 120],
        [ 18, 151, 118],
        [ 14, 148, 112],
        ...,
        [  8, 105,  78],
        [  7, 107,  79],
        [  5, 107,  79]],

       [[ 20, 153, 120],
        [ 17, 150, 117],
        [ 13, 147, 111],
        ...,
        [  9, 102,  73],
        [  8, 104,  74],
        [  7, 105,  75]],

       ...,

       [[ 10, 130,  96],
        [ 10, 130,  96],
        [ 10, 130,  96],
        ...,
        [ 14,  11,   7],
        [ 14,  11,   7],
        [ 14,  11,   7]],

       [[ 11, 131,  97],
        [ 11, 131,  97],
        [  9, 130,  96],
        ...,
        [ 13,  10,   6],
        [ 13,  10,   6],
        [ 12,   9,   5]],

       [[ 19, 140, 106],
        [  8, 129,  95],
        [  3, 124,  90],
        ...,
        [  9,  10,   6],
        [  9,  10,   6],
        [  9,  10,   6]]

In [6]:
# conversion to gray scale

# step one, take mean along the 3rd axis
mean_img = img.mean(axis=2)

In [7]:
mean_img

array([[97.66666667, 95.66666667, 91.33333333, ..., 65.33333333,
        64.66666667, 65.33333333],
       [97.66666667, 95.66666667, 91.33333333, ..., 63.66666667,
        64.33333333, 63.66666667],
       [97.66666667, 94.66666667, 90.33333333, ..., 61.33333333,
        62.        , 62.33333333],
       ...,
       [78.66666667, 78.66666667, 78.66666667, ..., 10.66666667,
        10.66666667, 10.66666667],
       [79.66666667, 79.66666667, 78.33333333, ...,  9.66666667,
         9.66666667,  8.66666667],
       [88.33333333, 77.33333333, 72.33333333, ...,  8.33333333,
         8.33333333,  8.33333333]])

In [8]:
# step two, convert the data to int (since cv2 only accepts integer values)
mean_img = mean_img.astype('int32')
mean_img

array([[97, 95, 91, ..., 65, 64, 65],
       [97, 95, 91, ..., 63, 64, 63],
       [97, 94, 90, ..., 61, 62, 62],
       ...,
       [78, 78, 78, ..., 10, 10, 10],
       [79, 79, 78, ...,  9,  9,  8],
       [88, 77, 72, ...,  8,  8,  8]])

In [9]:
# cv2's imshow only accepts images with 3 channels so let's create an image in 3 channels

# step 3, copy the original image to get the same dimensions
gr_img = img.copy()

#step 4, fill all the channels with same matrix
gr_img[:,:,0] = mean_img
gr_img[:,:,1] = mean_img
gr_img[:,:,2] = mean_img

In [10]:
# you can see that all pixels have same b g and r values. That is the property of grayscale images
gr_img

array([[[97, 97, 97],
        [95, 95, 95],
        [91, 91, 91],
        ...,
        [65, 65, 65],
        [64, 64, 64],
        [65, 65, 65]],

       [[97, 97, 97],
        [95, 95, 95],
        [91, 91, 91],
        ...,
        [63, 63, 63],
        [64, 64, 64],
        [63, 63, 63]],

       [[97, 97, 97],
        [94, 94, 94],
        [90, 90, 90],
        ...,
        [61, 61, 61],
        [62, 62, 62],
        [62, 62, 62]],

       ...,

       [[78, 78, 78],
        [78, 78, 78],
        [78, 78, 78],
        ...,
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[79, 79, 79],
        [79, 79, 79],
        [78, 78, 78],
        ...,
        [ 9,  9,  9],
        [ 9,  9,  9],
        [ 8,  8,  8]],

       [[88, 88, 88],
        [77, 77, 77],
        [72, 72, 72],
        ...,
        [ 8,  8,  8],
        [ 8,  8,  8],
        [ 8,  8,  8]]], dtype=uint8)

In [11]:
# view your image
cv2.imshow('grayscale',gr_img)
# to exit out of image
cv2.waitKey(0)

100