In [1]:
# Import the datasets module
import sklearn.datasets as skd
import numpy as np
import pandas as pd

In [86]:
# Checkout the entities of this module
dir(skd)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_svmlight_format',
 'base',
 'california_housing',
 'clear_data_home',
 'covtype',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_mldata',
 'fetch_olivetti_faces',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'kddcup99',
 'lfw',
 'load_boston',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_mlcomp',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circles',
 'make_classification',
 'make_friedman1',
 'make_friedman2',
 'make_friedman3',
 'make_gaussian_quantiles',
 'make_hastie_10_2',
 'make_low_rank

In [87]:
# calling "load_data" as a function
iris = skd.load_iris()

In [88]:
# Checking callable entities of this object now
dir(iris)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [5]:
# Checking the property: DESCR (stands for Description)
print(iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [89]:
# Let's pick out the data
xIris = iris.data
yIris = iris.target

In [90]:
xIris.shape

(150, 4)

In [91]:
# As per our decided convention, we are going to take the number of sampes along axis = 1 (columns)
X = xIris.T

In [92]:
# Same for output labels
Y = yIris.reshape(1,150)

### So effectively we have 150 samples for which we have input and output in corresponding indexes in X and Y

In [93]:
Y.shape

(1, 150)

In [94]:
X.shape

(4, 150)

In [96]:
Y

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

### We have three unique output labels right now: 0,1 and 2. Since we are doing binary classification, let's filter out the 2 for now

In [97]:
# preparing a 1-D filter
idx = yIris <= 1

In [98]:
# checking the filter out
idx

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [99]:
# filtering the data
Y = yIris[idx]

In [100]:
# data has only binary labels now
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [103]:
X.shape

(4, 150)

In [105]:
# filter X as well
X = X[:,idx]

In [106]:
# Corresponding values of inputs have been chosen
X.shape

(4, 100)

In [108]:
Y.shape

(100,)

### This is not the required shape. Seems like after filtering, Y became uni dimensional. Let's fix that.

In [109]:
Y = Y.reshape(1,100)

In [110]:
Y

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [111]:
# Using sklearn to standardize input
from sklearn.preprocessing import StandardScaler
# We retain our scaler "sc" in case we need to invert our inputs
sc = StandardScaler()
sc.fit(X)
X = sc.transform(X)

In [112]:
# X is now standardised
X

array([[ 1.351023  ,  1.43136473,  1.35847229,  1.35865503,  1.3119249 ,
         1.3198977 ,  1.29706355,  1.35489373,  1.37783158,  1.39536393,
         1.35084454,  1.31697617,  1.4064146 ,  1.3331083 ,  1.34976381,
         1.26369822,  1.32624394,  1.3600304 ,  1.37651426,  1.28853176,
         1.4058958 ,  1.32061434,  1.24472875,  1.41746429,  1.29944317,
         1.43733272,  1.37198868,  1.36370722,  1.38754866,  1.34715063,
         1.38704608,  1.43087011,  1.22203598,  1.26214705,  1.39536393,
         1.40591898,  1.40842139,  1.39536393,  1.35623308,  1.3703935 ,
         1.34584928,  1.54277843,  1.30368712,  1.36838709,  1.28273619,
         1.42848003,  1.27686857,  1.33807733,  1.33576544,  1.38019877,
         1.42439522,  1.39427847,  1.38961667,  1.38472142,  1.40597899,
         1.2729173 ,  1.34080392,  1.4124491 ,  1.39565142,  1.34856954,
         1.40213637,  1.39472039,  1.42899153,  1.30649423,  1.45769298,
         1.44687869,  1.26069096,  1.35764502,  1.3

In [113]:
# mean 0
X.mean()

4.440892098500626e-18

In [114]:
# variance is 1
X.std()

1.0

In [115]:
# using sc to revert the transformation
sc.inverse_transform(X)

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
        3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3. ,
        3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
        3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
        3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3. , 2.8, 3.

In [116]:
# Initialization of our network

# number of inputs
n0 = 4
# number of hidden units
n1 = 20
# number of outputs
n2 = 1
# number of samples
m = 100

# We initialize our weights in a random normal fashion to aid the backpropagation
W1 = np.random.randn(n1,n0) * 0.01
W2 = np.random.randn(n2,n1) * 0.01

# We may initailize the biases as 0 without hampering backpropagation
B1 = np.zeros((n1,1))
B2 = np.zeros((n2,1))

In [118]:
# good old sigmoid function
def sigmoid(arr):
    return 1/(1+np.exp(-arr))

In [119]:
# testing
sigmoid(0)

0.5

In [121]:
# forward propagation

# As explained, the output of first layer can be obtained by taking the dot product of weights and inputs and then
# broadcasting the biases
Z1 = W1.dot(X) + B1
# activating the first layer (the hidden layer)
A1 = sigmoid(Z1)

# The next layer uses output of previous layer as input
Z2 = W2.dot(A1) + B2
# The decision
A2 = sigmoid(Z2)

In [122]:
# backprop

# For sigmoid backprop and binary logloss, our derivative of cost w.r.t Z2 is:
dZ2 = A2 - Y
# This is a formula you guys will need to commit to memory or use as a reference. It requires quite a bit of work to derive
dW2 = (1/m) * (dZ2.dot(A1.T))
# Dervative of biases is usually just what derivative of weights is, excluding the multiplication with inputs from previous layer
dB2 = (1/m) * (dZ2.mean(axis = 1,keepdims = True))

# Another formula to remember dZ(of layer L) = W(of layer L).T.dot(dZ(L+1)) * derivative expression
# The derivative expression for sigmoid is A1 * (1 - A1).
# If the activation of this layer had been tanh, the derivative expression would have been (1 - A1**2)
dZ1 = (W2.T).dot(dZ2) * A1 * (1 - A1)
dW1 = (1/m) * (dZ1.dot(X.T))
dB1 = (1/m) * (dZ1.mean(axis = 1,keepdims = True)) 

In [123]:
# Updating parameters
lr = 0.01

W1 = W1 - lr * dW1
W2 = W2 - lr * dW2

B1 = B1 - lr * dB1
B2 = B2 - lr * dB2

In [126]:
# Binary cross entropy loss
def logCost(A,Y):
    return -(Y*np.log(A) + (1-Y)*np.log(1-A)).sum()

In [127]:
# testing
logCost(A2,Y)

69.32020142125276

In [128]:
# Re - initialization. We have tested stuff. We will now run the network from start.

n0 = 4
n1 = 1
n2 = 1
m = 100

W1 = np.random.randn(n1,n0) * 0.01
W2 = np.random.randn(n2,n1) * 0.01

B1 = np.zeros((n1,1))
B2 = np.zeros((n2,1))

costs = []

In [129]:
epochs = 10000
lr = 2

for i in range(epochs):
    # forward propagation

    Z1 = W1.dot(X) + B1
    A1 = sigmoid(Z1)

    Z2 = W2.dot(A1) + B2
    A2 = sigmoid(Z2)
    
    # print cost
    cost = logCost(A2,Y)
    if i%50 == 0:
        print("cost after",str(i),"iterations is:",cost)
    costs.append(cost)
    
    # backprop
    dZ2 = A2 - Y
    dW2 = (1/m) * (dZ2.dot(A1.T))
    dB2 = (1/m) * (dZ2.mean(axis = 1,keepdims = True))

    dZ1 = (W2.T).dot(dZ2) * A1 * (1 - A1)
    dW1 = (1/m) * (dZ1.dot(X.T))
    dB1 = (1/m) * (dZ1.mean(axis = 1,keepdims = True)) 
    
    # weight update
    W1 = W1 - lr * dW1
    W2 = W2 - lr * dW2

    B1 = B1 - lr * dB1
    B2 = B2 - lr * dB2

cost after 0 iterations is: 69.31405172755606
cost after 50 iterations is: 51.299935575636205
cost after 100 iterations is: 31.77656569163836
cost after 150 iterations is: 26.287035704300415
cost after 200 iterations is: 22.47868615668359
cost after 250 iterations is: 19.551569995343243
cost after 300 iterations is: 17.2245536526782
cost after 350 iterations is: 15.337302739005448
cost after 400 iterations is: 13.783016055057466
cost after 450 iterations is: 12.486107559253574
cost after 500 iterations is: 11.391389946224441
cost after 550 iterations is: 10.457727250402018
cost after 600 iterations is: 9.6539532393557
cost after 650 iterations is: 8.956120592906258
cost after 700 iterations is: 8.345594226536715
cost after 750 iterations is: 7.807703320455867
cost after 800 iterations is: 7.330773097668843
cost after 850 iterations is: 6.905419708907707
cost after 900 iterations is: 6.524030257153012
cost after 950 iterations is: 6.18037487193314
cost after 1000 iterations is: 5.869314

cost after 9000 iterations is: 0.6010714698321415
cost after 9050 iterations is: 0.5976581184040086
cost after 9100 iterations is: 0.5942830964360065
cost after 9150 iterations is: 0.5909457643359327
cost after 9200 iterations is: 0.5876454966231165
cost after 9250 iterations is: 0.5843816815422673
cost after 9300 iterations is: 0.5811537206898741
cost after 9350 iterations is: 0.5779610286527295
cost after 9400 iterations is: 0.5748030326581254
cost after 9450 iterations is: 0.5716791722352643
cost after 9500 iterations is: 0.5685888988874555
cost after 9550 iterations is: 0.5655316757747574
cost after 9600 iterations is: 0.5625069774066022
cost after 9650 iterations is: 0.5595142893441108
cost after 9700 iterations is: 0.556553107911684
cost after 9750 iterations is: 0.5536229399175863
cost after 9800 iterations is: 0.5507233023831574
cost after 9850 iterations is: 0.5478537222803637
cost after 9900 iterations is: 0.5450137362773873
cost after 9950 iterations is: 0.5422028904919678


### Cost has reduced to lesser than 1 so results should be quite good.

In [130]:
# gives an array of zeros
pred = np.zeros(A2.shape)

In [131]:
pred

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [132]:
# Let's just say whatever is closer to 0 is a 0 and whatever is closer to 1 is a 1
pred[A2 > 0.5] = 1

In [133]:
pred

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [135]:
# Perfect predictions!
pred - Y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

### Now that we have worked on binary classification, let's try multi-class classification as well

In [136]:
# reload the data
iris = skd.load_iris()

In [137]:
xIris = iris.data
yIris = iris.target

In [138]:
xIris.shape

(150, 4)

In [150]:
X = xIris.T

In [151]:
from sklearn.preprocessing import OneHotEncoder
# We will one hot encode the output labels since there are more than two categories
ohe = OneHotEncoder()

In [153]:
Y = yIris.T

In [154]:
# fitting the data
ohe.fit(Y.reshape(-1, 1))

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [155]:
# initial form
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [156]:
# one hot encoding
Y = ohe.transform(Y.reshape(-1, 1)).toarray()

In [157]:
Y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [158]:
# check the shape
Y.shape

(150, 3)

## The convention which we are following requires the samples to be along columns so:

In [159]:
Y = Y.T

In [160]:
Y.shape

(3, 150)

In [161]:
# Initialization: This time we initialize parameters for multi-class classification

n0 = 4
n1 = 20
# There are 3 outputs. Each will give a likelihood output being the corresponding category
n2 = 3
# number of samples is 150 now
m = 150

W1 = np.random.randn(n1,n0) * 0.01
W2 = np.random.randn(n2,n1) * 0.01

B1 = np.zeros((n1,1))
B2 = np.zeros((n2,1))

In [163]:
# defining our cross entropy loss function
def logCostMulti(A,Y):
    assert A.shape == Y.shape
    a,m = A.shape
    
    loss = -(Y * np.log(A)).sum()
       
    return loss

In [67]:
# the softmax function.
def softmax(Z):
    return np.exp(Z)/(np.exp(Z).sum(axis = 0))

In [164]:
# We will just run the network this time. We have experience of building a network already.
epochs = 400000
lr = 0.1

for i in range(epochs):
    # forward propagation

    Z1 = W1.dot(X) + B1
    A1 = sigmoid(Z1)

    Z2 = W2.dot(A1) + B2
    # This time, the activation function is softmax function
    A2 = softmax(Z2)
    
    # print cost
    cost = logCostMulti(A2,Y)
    if i%500 == 0:
        print("cost after",str(i),"iterations is:",cost)
    costs.append(cost)
    
    # backprop
    dZ2 = A2 - Y
    dW2 = (1/m) * (dZ2.dot(A1.T))
    dB2 = (1/m) * (dZ2.mean(axis = 1,keepdims = True))

    dZ1 = (W2.T).dot(dZ2) * A1 * (1 - A1)
    dW1 = (1/m) * (dZ1.dot(X.T))
    dB1 = (1/m) * (dZ1.mean(axis = 1,keepdims = True)) 
    
    # weight update
    W1 = W1 - lr * dW1
    W2 = W2 - lr * dW2

    B1 = B1 - lr * dB1
    B2 = B2 - lr * dB2
    
# Brace yourself. This is going to take time.

cost after 0 iterations is: 164.80316853252853
cost after 500 iterations is: 42.28699666463442
cost after 1000 iterations is: 20.033664176652522
cost after 1500 iterations is: 14.636033462857725
cost after 2000 iterations is: 12.436988813155255
cost after 2500 iterations is: 11.26412313241101
cost after 3000 iterations is: 10.54090859359587
cost after 3500 iterations is: 10.052955041716906
cost after 4000 iterations is: 9.702570446869787
cost after 4500 iterations is: 9.439000767245108
cost after 5000 iterations is: 9.233397719212443
cost after 5500 iterations is: 9.068250555751048
cost after 6000 iterations is: 8.932373685551466
cost after 6500 iterations is: 8.818318683934594
cost after 7000 iterations is: 8.720949574838553
cost after 7500 iterations is: 8.636617760581409
cost after 8000 iterations is: 8.562663781102966
cost after 8500 iterations is: 8.497105413728185
cost after 9000 iterations is: 8.438436131268055
cost after 9500 iterations is: 8.385491139018825
cost after 10000 it

cost after 83000 iterations is: 6.125314163388022
cost after 83500 iterations is: 6.109281255347376
cost after 84000 iterations is: 6.093479924745926
cost after 84500 iterations is: 6.077912177449284
cost after 85000 iterations is: 6.062579121374469
cost after 85500 iterations is: 6.047481014395427
cost after 86000 iterations is: 6.032617315677572
cost after 86500 iterations is: 6.017986739567713
cost after 87000 iterations is: 6.003587311214751
cost after 87500 iterations is: 5.989416423155323
cost after 88000 iterations is: 5.975470892163403
cost after 88500 iterations is: 5.961747015732849
cost after 89000 iterations is: 5.948240627633366
cost after 89500 iterations is: 5.934947152053311
cost after 90000 iterations is: 5.92186165591375
cost after 90500 iterations is: 5.908978899007821
cost after 91000 iterations is: 5.896293381684941
cost after 91500 iterations is: 5.8837993898619505
cost after 92000 iterations is: 5.8714910372000935
cost after 92500 iterations is: 5.85936230433962


cost after 165000 iterations is: 4.183052721227546
cost after 165500 iterations is: 4.1689504547417515
cost after 166000 iterations is: 4.154879401928068
cost after 166500 iterations is: 4.140841227690925
cost after 167000 iterations is: 4.126837543626709
cost after 167500 iterations is: 4.1128699085575615
cost after 168000 iterations is: 4.098939829133405
cost after 168500 iterations is: 4.085048760494077
cost after 169000 iterations is: 4.071198106984241
cost after 169500 iterations is: 4.057389222914069
cost after 170000 iterations is: 4.0436234133594295
cost after 170500 iterations is: 4.029901934995597
cost after 171000 iterations is: 4.016225996959269
cost after 171500 iterations is: 4.002596761733949
cost after 172000 iterations is: 3.989015346054307
cost after 172500 iterations is: 3.975482821825533
cost after 173000 iterations is: 3.9620002170541513
cost after 173500 iterations is: 3.9485685167870663
cost after 174000 iterations is: 3.93518866405602
cost after 174500 iteration

cost after 245500 iterations is: 2.636193353382587
cost after 246000 iterations is: 2.630771122519646
cost after 246500 iterations is: 2.625384353613091
cost after 247000 iterations is: 2.620032695006972
cost after 247500 iterations is: 2.6147157960731318
cost after 248000 iterations is: 2.6094333072426097
cost after 248500 iterations is: 2.604184880034744
cost after 249000 iterations is: 2.5989701670836305
cost after 249500 iterations is: 2.5937888221622005
cost after 250000 iterations is: 2.5886405002039172
cost after 250500 iterations is: 2.5835248573218754
cost after 251000 iterations is: 2.5784415508257257
cost after 251500 iterations is: 2.5733902392359664
cost after 252000 iterations is: 2.568370582296137
cost after 252500 iterations is: 2.563382240982529
cost after 253000 iterations is: 2.5584248775115843
cost after 253500 iterations is: 2.5534981553452023
cost after 254000 iterations is: 2.548601739193654
cost after 254500 iterations is: 2.5437352950163583
cost after 255000 it

cost after 325000 iterations is: 2.009092685793024
cost after 325500 iterations is: 2.0054135438193077
cost after 326000 iterations is: 2.001727737494916
cost after 326500 iterations is: 1.998035372863487
cost after 327000 iterations is: 1.9943365670690658
cost after 327500 iterations is: 1.990631448150669
cost after 328000 iterations is: 1.986920154814657
cost after 328500 iterations is: 1.9832028361855882
cost after 329000 iterations is: 1.979479651536187
cost after 329500 iterations is: 1.9757507699972345
cost after 330000 iterations is: 1.9720163702484572
cost after 330500 iterations is: 1.9682766401911713
cost after 331000 iterations is: 1.9645317766039407
cost after 331500 iterations is: 1.960781984782164
cost after 332000 iterations is: 1.9570274781631471
cost after 332500 iterations is: 1.9532684779374723
cost after 333000 iterations is: 1.9495052126483292
cost after 333500 iterations is: 1.9457379177799867
cost after 334000 iterations is: 1.9419668353366888
cost after 334500 i

In [165]:
# Let's infer the predictions now
pred = np.zeros(A2.shape[1])

In [166]:
# pred s an array of zeros right now
pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [81]:
# Reminding you that A2 contains output for 150 samples 
A2.shape[1]

150

In [169]:
for i in range(A2.shape[1]):

    # So we just say that our prediction is equal to category of corresponding index of output node that gives the maximum output
    val = np.argmax(A2[:,i])
    pred[i] = val

In [170]:
pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [171]:
yIris

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [173]:
# perfect prediction yet again
pred - yIris

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## An exercise to try: Split this data into test and train. Train a network on train data and see how well the network does on test data.